repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        exclude: "mkdocs.yml"

  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--without-hashes","-f", "requirements.txt", "-o", "requirements.txt"]
      - id: poetry-install
